# Generated by Django 4.2.6 on 2023-10-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
