# Generated by Django 4.2.6 on 2023-11-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed_alter_task_datetime_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-datetime_created']},
        ),
    ]
